### ISSUE TITLE
React-Redux-group_Project

### ISSUE THREAD

**Issue by V-Blaze** [KIsmoilov/Space-Traveler-s-Hub#22]
- This is the link to the Group Project: https://github.com/KIsmoilov/Space-Traveler-s-Hub/projects/1
- We are a group of two.

**Comment by Abenezer-Tilahun** [comment]
Hi @V-Blaze @KIsmoilov 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️Successfully set up your Kanban board
✔️ Provide link to your GitHub project and how many people there are in your team.
✔️ Successfully all cards are assigned to team members

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
